/**
 * API key management for /api/v2/* commercial endpoints.
 *
 * Keys are stored as scrypt-hashed entries in a JSON file (path from
 * `API_KEYS_FILE` env, default `.api-keys.json` in repo root).
 *
 * The plaintext key is only ever shown when generated by scripts/gen-api-key.js.
 * Verification uses timingSafeEqual to resist timing attacks.
 */

import { promises as fs } from 'fs';
import path from 'path';
import crypto from 'crypto';

export type ApiKeyTier = 'free' | 'pro' | 'scale' | 'enterprise';

export interface ApiKeyRecord {
  id: string;
  label: string;
  tier: ApiKeyTier;
  hash: string;
  salt: string;
  createdAt: string;
  lastUsedAt: string | null;
  callCount: number;
  enabled: boolean;
}

export interface ApiKeyStore {
  version: 1;
  keys: ApiKeyRecord[];
}

const SCRYPT_KEYLEN = 64;
const KEY_PREFIX = 'mwm_';

function getStorePath(): string {
  return process.env.API_KEYS_FILE
    ?? path.join(process.cwd(), '.api-keys.json');
}

async function readStore(): Promise<ApiKeyStore> {
  const p = getStorePath();
  try {
    const raw = await fs.readFile(p, 'utf-8');
    return JSON.parse(raw) as ApiKeyStore;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
      if (process.env.NODE_ENV !== 'test') {
        console.warn(`[api-keys] store not found at ${p}; starting empty`);
      }
      return { version: 1, keys: [] };
    }
    throw err;
  }
}

async function writeStore(store: ApiKeyStore): Promise<void> {
  const p = getStorePath();
  const tmp = `${p}.tmp`;
  await fs.writeFile(tmp, JSON.stringify(store, null, 2), { mode: 0o600 });
  await fs.rename(tmp, p);
}

function hashKey(plaintext: string, salt: string): Promise<string> {
  return new Promise((resolve, reject) => {
    crypto.scrypt(plaintext, salt, SCRYPT_KEYLEN, (err, derived) => {
      if (err) return reject(err);
      resolve(derived.toString('hex'));
    });
  });
}

function safeEqualHex(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  try {
    return crypto.timingSafeEqual(Buffer.from(a, 'hex'), Buffer.from(b, 'hex'));
  } catch {
    return false;
  }
}

/**
 * Generate a fresh API key. Returns the plaintext (show to user once) and the record.
 * The record is persisted to the store; the plaintext is never stored.
 */
export async function generateApiKey(
  label: string,
  tier: ApiKeyTier
): Promise<{ plaintext: string; record: Omit<ApiKeyRecord, 'hash' | 'salt'> }> {
  const random = crypto.randomBytes(24).toString('base64url');
  const plaintext = `${KEY_PREFIX}${random}`;
  const salt = crypto.randomBytes(16).toString('hex');
  const hash = await hashKey(plaintext, salt);

  const record: ApiKeyRecord = {
    id: crypto.randomUUID(),
    label,
    tier,
    hash,
    salt,
    createdAt: new Date().toISOString(),
    lastUsedAt: null,
    callCount: 0,
    enabled: true,
  };

  const store = await readStore();
  store.keys.push(record);
  await writeStore(store);

  const { hash: _h, salt: _s, ...safeRecord } = record;
  return { plaintext, record: safeRecord };
}

/**
 * Verify a presented API key. Returns the matching record if valid, else null.
 * Increments call count and updates lastUsedAt on success.
 */
export async function verifyApiKey(
  presented: string | null | undefined
): Promise<ApiKeyRecord | null> {
  if (!presented || !presented.startsWith(KEY_PREFIX)) return null;

  const store = await readStore();
  for (const record of store.keys) {
    if (!record.enabled) continue;
    const computed = await hashKey(presented, record.salt);
    if (safeEqualHex(computed, record.hash)) {
      // Update usage stats (best-effort, don't fail the request if write fails)
      record.lastUsedAt = new Date().toISOString();
      record.callCount += 1;
      try {
        await writeStore(store);
      } catch (err) {
        console.warn('[api-keys] failed to update usage stats:', err);
      }
      return record;
    }
  }
  return null;
}

/**
 * List API keys (without hashes/salts) for admin viewing.
 */
export async function listApiKeys(): Promise<Omit<ApiKeyRecord, 'hash' | 'salt'>[]> {
  const store = await readStore();
  return store.keys.map(({ hash: _h, salt: _s, ...rest }) => rest);
}

/**
 * Revoke (disable) a key by ID.
 */
export async function revokeApiKey(id: string): Promise<boolean> {
  const store = await readStore();
  const record = store.keys.find((k) => k.id === id);
  if (!record) return false;
  record.enabled = false;
  await writeStore(store);
  return true;
}

export const TIER_RATE_LIMITS: Record<ApiKeyTier, { perMinute: number; burst: number }> = {
  free: { perMinute: 60, burst: 100 },
  pro: { perMinute: 600, burst: 1000 },
  scale: { perMinute: 6000, burst: 10000 },
  enterprise: { perMinute: Number.POSITIVE_INFINITY, burst: Number.POSITIVE_INFINITY },
};
